### ISSUE TITLE
Regularly Scheduled Meeting Topic

### ISSUE THREAD

**Issue by dapperfu** [GRPUG/GrandRapidsPythonUsersGroup#1]
1. Free alternative to MeetUp, if needed.
2. I wanted to play around with the new GitHub features.

**Comment by dapperfu** [comment]
Can anyone talk about how to publish so something is in 'pip'? I have yet to publish anything officially.

**Comment by jacebrowning** [comment]
@jed-frey Yeah, I could definitely do a refresher on Python packaging and distribution.

**Comment by brousch** [comment]
It looks like we last covered this as a meeting in 2014, so there should be plenty of changes. https://www.meetup.com/grpython/events/163320652/

I could pull together a talk about building DEBs, but Docker would probably be a more popular adjacent topic.

**Comment by jacebrowning** [comment]
I could go over some of the history, but I'll mostly be covering `poetry` and `pipx`.

**Comment by dapperfu** [comment]
Some other projects I found:

https://github.com/jlesquembre/autopilot (Last updated 2016, but it author says it 'works')

https://flit.readthedocs.io/en/latest/
