### ISSUE TITLE
Meeting Topic for 2019-12-16

### ISSUE THREAD

**Issue by brousch** [GRPUG/GrandRapidsPythonUsersGroup#2]
Ideas from previous discussions:

- Python 3.8
- Bring your own project / Social time

**Comment by dapperfu** [comment]
I can show my [mPerks Python module](https://github.com/jed-frey/python_Meijer)

Which you can use to get current gas prices, at all stores (and make plots):

![image](https://user-images.githubusercontent.com/223258/69263144-b8b19d00-0b92-11ea-913b-f4ef5fc33a71.png)

[Or automatically clip coupons](https://github.com/jed-frey/python_Meijer/blob/master/Meijer2_ClipAllCoupons.ipynb).

**Comment by dapperfu** [comment]
This project looks neat if you use Notebooks a lot: https://www.fast.ai/2019/12/02/nbdev/

**Comment by dapperfu** [comment]
```meijer``` shopping list manipulation.

![image](https://user-images.githubusercontent.com/223258/69969428-66ee0880-14ea-11ea-9e61-88d68e68edb0.png)
